# /etc/corosync/corosync.conf — cyntia y cyntia-backup
# Configuración del cluster Proxmox VE
# Versión: 5 (actualizada tras incorporar two_node y corrección de IPs)

logging {
  debug: off
  to_syslog: yes
}

nodelist {
  node {
    name: cyntia
    nodeid: 1
    quorum_votes: 1
    ring0_addr: 192.168.3.100
  }
  node {
    name: cyntia-backup
    nodeid: 2
    quorum_votes: 1
    ring0_addr: 192.168.3.101
  }
}

quorum {
  provider: corosync_votequorum
  two_node: 1
}

totem {
  cluster_name: cyntia-cluster
  config_version: 5
  interface {
    linknumber: 0
  }
  ip_version: ipv4-6
  link_mode: passive
  secauth: on
  version: 2
}
