# /etc/sysctl.conf
# Parámetros del kernel añadidos para el proyecto Cyntia

# Habilitar IP forwarding para que Proxmox pueda actuar como router
# entre las VLANs y hacer NAT hacia internet
net.ipv4.ip_forward=1

# Requerido por OpenSearch (Wazuh Indexer) para el uso de mmap en sus índices.
# OpenSearch usa memory-mapped files para acceder a los segmentos de índice
# de forma eficiente. Sin este valor, OpenSearch falla al arrancar.
vm.max_map_count=262144
